### ISSUE TITLE
Cannot delete asset

### ISSUE THREAD

**Issue by flablog** [cgwire/gazu#15]
If I get an asset, I can not delete it with current gazu commands, it rises a RouteNotFoundException.

```
> a = gazu.asset.get_asset_by_name({'id':"7896a9aa-dd4b-4abb-93a5-d96bd9828c7f"}, 'Ag10_baguette')
> print(a)
{u'entity_type_id': u'ff94db8f-2345-465e-8561-22dc24c2fd10', u'description': u'', u'parent_id': None, u'preview_file_id': None, u'entities_out': [], u'created_at': u'2017-12-12T13:35:09.779624', u'shotgun_id': None, u'updated_at': u'2017-12-12T13:35:09.779633', u'canceled': False, u'type': u'Entity', u'entities_in': [], u'project_id': u'7896a9aa-dd4b-4abb-93a5-d96bd9828c7f', u'data': None, u'id': u'02835ad0-158a-41df-b836-f7570aae2c07', u'name': u'Ag10_baguette'}

> gazu.asset.remove_asset(a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/u/lodeve-kitsu-webservices/gazu/gazu/asset.py", line 99, in remove_asset
    asset["id"]
  File "/u/lodeve-kitsu-webservices/gazu/gazu/client.py", line 145, in delete
    check_status(response.status_code, path)
  File "/u/lodeve-kitsu-webservices/gazu/gazu/client.py", line 155, in check_status
    raise RouteNotFoundException(path)
gazu.exception.RouteNotFoundException: data/projects/7896a9aa-dd4b-4abb-93a5-d96bd9828c7f/asset-types/ff94db8f-2345-465e-8561-22dc24c2fd10/assets/02835ad0-158a-41df-b836-f7570aae2c07
```

**Comment by frankrousseau** [comment]
It should be fixed in last release. Can you confirm?

**Comment by flablog** [comment]
Apparently I'm up to date with gazu, zou (api 3.3.9) and kitsu
and I've the same issue

**Comment by flablog** [comment]
Tested with api 0.3.11 with another asset
same issue ?

gazu.exception.RouteNotFoundException: data/projects/6854c5c6-0c10-4049-aaf3-0e154937e705/asset-types/87f26397-7d0f-4470-8ca0-024edac56905/assets/02917f6b-d8d3-48db-8fba-54cf86ad18e4

**Comment by frankrousseau** [comment]
Did you update Gazu too?
