### ISSUE TITLE
Get notifications : ServerError

### ISSUE THREAD

**Issue by manuelrais** [cgwire/gazu#174]
Hi
We have a server error when retrieving user notifications.  
Only one kitsu person have this problem. It's maybe due to a big number of notifications (+16000).

Here's the traceback : 
```
A server error occured!Server stacktrace:
Traceback (most recent call last):
  File "/opt/zou/zouenv/lib/python3.5/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/zou/zouenv/lib/python3.5/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/flask_jwt_extended/view_decorators.py", line 103, in wrapper
    return fn(*args, **kwargs)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/zou/app/blueprints/crud/base.py", line 296, in put
    instance = self.get_model_or_404(instance_id)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/zou/app/blueprints/crud/base.py", line 220, in get_model_or_404
    instance = self.model.get(instance_id)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/zou/app/models/base.py", line 40, in get
    return cls.query.get(id)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 1018, in get
    return self._get_impl(ident, loading.load_on_pk_identity)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 1135, in _get_impl
    return db_load_fn(self, primary_key_identity)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/sqlalchemy/orm/loading.py", line 286, in load_on_pk_identity
    return q.one()
  File "/opt/zou/zouenv/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 3490, in one
    ret = self.one_or_none()
  File "/opt/zou/zouenv/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 3459, in one_or_none
    ret = list(self)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/sqlalchemy/orm/loading.py", line 100, in instances
    cursor.close()
  File "/opt/zou/zouenv/lib/python3.5/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    with_traceback=exc_tb,
  File "/opt/zou/zouenv/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/opt/zou/zouenv/lib/python3.5/site-packages/sqlalchemy/orm/loading.py", line 80, in instances
    rows = [proc(row) for row in fetch]
  File "/opt/zou/zouenv/lib/python3.5/site-packages/sqlalchemy/orm/loading.py", line 80, in <listcomp>
    rows = [proc(row) for row in fetch]
  File "/opt/zou/zouenv/lib/python3.5/site-packages/sqlalchemy/orm/loading.py", line 588, in _instance
    populators,
  File "/opt/zou/zouenv/lib/python3.5/site-packages/sqlalchemy/orm/loading.py", line 725, in _populate_full
    dict_[key] = getter(row)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/sqlalchemy/sql/type_api.py", line 1283, in process
    return process_value(value, dialect)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/sqlalchemy_utils/types/choice.py", line 172, in process_result_value
    return self.type_impl.process_result_value(value, dialect)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/sqlalchemy_utils/types/choice.py", line 199, in process_result_value
    return Choice(value, self.choices_dict[value])
KeyError: 'Notification'Error message:
'Notification'---------------------------------------------------------------------------
ServerErrorException                      Traceback (most recent call last)
<ipython-input-44-6f749ab382c2> in <module>
      2     n.update(read=True)
      3     print(n)
----> 4     gazu.client.put(f'/data/notifications/{n.get("id")}', n)
      5     break
      6 /srv/dev/prod/gazu/gazu/client.py in put(path, data, client)
    225         headers=make_auth_header(client=client)
    226     )
--> 227     check_status(response, path)
    228     return response.json()
    229 /srv/dev/prod/gazu/gazu/client.py in check_status(request, path)
    296         except:
    297             print(request.text)
--> 298         raise ServerErrorException(path)
    299     return status_code
    300 ServerErrorException: /data/notifications/8c3e0242-29d1-4167-aae1-02d478ee0dd0
```

**Comment by frankrousseau** [comment]
It's a problem with a notification that is malformed. Can you try to remove directly this notification?
