### ISSUE TITLE
get_episode_by_name raises ServerErrorException

### ISSUE THREAD

**Issue by aboellinger** [cgwire/gazu#42]
The following methods appear to be broken. 

```py
gazu.shot.get_episode_by_name
gazu.shot.get_sequence_by_name
gazu.scene.get_scene_by_name
gazu.shot.get_shot_by_name
```

Error seems to be related to the project.id formatting, but a call to `gazu.asset.get_asset_by_name(project, 'Perso1')` with the same `project` will succeed.

## Local error

They will fail with a `ServerErrorException` (here from a `pytest` run)

```
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
python\test\test_explorer.py:25: in default_preferences
    episode = pipeline_client.shot.get_episode_by_name(project, 'e001')
..\gazu\gazu\cache.py:147: in wrapper
    kwargs
..\gazu\gazu\cache.py:66: in insert_value
    returned_value = function(*args, **kwargs)
..\gazu\gazu\shot.py:78: in get_episode_by_name
    episode_name
..\gazu\gazu\client.py:177: in fetch_first
    entries = get(url_path_join('data', path))
..\gazu\gazu\client.py:97: in get
    check_status(response, path)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

request = <Response [500]>
path = 'data/episodes?project_id=9405c0a7-d503-497d-bf16-bd82a5707c22&name=e001'

    def check_status(request, path):
        """
        Raise an exception related to status code, if the status code does not match
        a success code.
        """
        status_code = request.status_code
        if (status_code == 404):
            raise RouteNotFoundException(path)
        elif (status_code == 403):
            raise NotAllowedException(path)
        elif (status_code == 400):
            text = request.json().get("message", "No additional information")
            raise ParameterException(path, text)
        elif (status_code == 405):
            raise MethodNotAllowedException(path)
        elif (status_code in [401, 422]):
            raise NotAuthenticatedException(path)
        elif (status_code in [500, 502]):
            print(request.text)
>           raise ServerErrorException(path)
E           ServerErrorException: data/episodes?project_id=9405c0a7-d503-497d-bf16-bd82a5707c22&name=e001
```

## Server Error

gunicorn error log on the server side : 

```
[2018-12-28 12:53:57 +0000] [30859] [ERROR] Error handling request //data/episodes?project_id=9405c0a7-d503-497d-bf16-bd82a5707c22&name=e001
Traceback (most recent call last):
  File "/opt/zou/virtualenv/lib/python2.7/site-packages/gunicorn/workers/base_async.py", line 56, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/opt/zou/virtualenv/lib/python2.7/site-packages/gunicorn/workers/ggevent.py", line 160, in handle_request
    addr)
  File "/opt/zou/virtualenv/lib/python2.7/site-packages/gunicorn/workers/base_async.py", line 107, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/opt/zou/virtualenv/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/zou/virtualenv/lib/python2.7/site-packages/flask_socketio/__init__.py", line 43, in __call__
    start_response)
  File "/opt/zou/virtualenv/lib/python2.7/site-packages/engineio/middleware.py", line 49, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/zou/virtualenv/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/opt/zou/virtualenv/lib/python2.7/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/opt/zou/virtualenv/lib/python2.7/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/opt/zou/virtualenv/lib/python2.7/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/opt/zou/virtualenv/lib/python2.7/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/opt/zou/virtualenv/lib/python2.7/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/opt/zou/virtualenv/lib/python2.7/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/opt/zou/virtualenv/lib/python2.7/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/opt/zou/virtualenv/lib/python2.7/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/opt/zou/virtualenv/lib/python2.7/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/opt/zou/virtualenv/lib/python2.7/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/opt/zou/virtualenv/lib/python2.7/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/opt/zou/virtualenv/lib/python2.7/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/opt/zou/virtualenv/lib/python2.7/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/opt/zou/virtualenv/lib/python2.7/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/opt/zou/virtualenv/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/zou/virtualenv/lib/python2.7/site-packages/flask_restful/__init__.py", line 268, in error_router
    return self.handle_error(e)
  File "/opt/zou/virtualenv/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/zou/virtualenv/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/zou/virtualenv/lib/python2.7/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/opt/zou/virtualenv/lib/python2.7/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/opt/zou/virtualenv/lib/python2.7/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/opt/zou/virtualenv/lib/python2.7/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/opt/zou/virtualenv/lib/python2.7/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/opt/zou/virtualenv/lib/python2.7/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/opt/zou/virtualenv/lib/python2.7/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/opt/zou/virtualenv/lib/python2.7/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/opt/zou/virtualenv/lib/python2.7/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/opt/zou/virtualenv/lib/python2.7/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/opt/zou/virtualenv/lib/python2.7/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/opt/zou/virtualenv/lib/python2.7/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/opt/zou/virtualenv/lib/python2.7/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/opt/zou/virtualenv/lib/python2.7/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/opt/zou/virtualenv/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/zou/virtualenv/lib/python2.7/site-packages/flask_restful/__init__.py", line 268, in error_router
    return self.handle_error(e)
  File "/opt/zou/virtualenv/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/zou/virtualenv/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/zou/virtualenv/lib/python2.7/site-packages/flask_restful/__init__.py", line 477, in wrapper
    resp = resource(*args, **kwargs)
  File "/opt/zou/virtualenv/lib/python2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/opt/zou/virtualenv/lib/python2.7/site-packages/flask_restful/__init__.py", line 587, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/opt/zou/virtualenv/lib/python2.7/site-packages/flask_jwt_extended/view_decorators.py", line 38, in wrapper
    return fn(*args, **kwargs)
  File "/opt/zou/zou/app/blueprints/shots/resources.py", line 326, in get
    user_service.check_project_access(criterions)
  File "/opt/zou/zou/app/services/user_service.py", line 308, in check_project_access
    check_belong_to_project(project_id)
  File "/opt/zou/zou/app/services/user_service.py", line 294, in check_belong_to_project
    project = projects_service.get_project(project_id)
  File "/opt/zou/zou/app/services/projects_service.py", line 154, in get_project
    return get_project_raw(project_id).serialize()
  File "/opt/zou/zou/app/services/projects_service.py", line 139, in get_project_raw
    project = Project.get(project_id)
  File "/opt/zou/zou/app/models/base.py", line 42, in get
    return cls.query.get(id)
  File "/opt/zou/virtualenv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 871, in get
    ident, loading.load_on_ident)
  File "/opt/zou/virtualenv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 886, in _get_impl
    ','.join("'%s'" % c for c in mapper.primary_key))
InvalidRequestError: Incorrect number of values in identifier to formulate primary key for query.get(); primary key columns are 'project.id'
```

**Comment by frankrousseau** [comment]
Hello @aboellinger,

This problem should not appear anymore if you use the latest versions of Zou and Gazu.
