### ISSUE TITLE
Trying to update task-assignees: "AttributeError: 'str' object has no attribute '_sa_instance_state'"

### ISSUE THREAD

**Issue by kguyaux** [cgwire/gazu#61]
Hello everyone, I'm trying to update task-data using gazu.
I'm using the command:
`gazu.task.client.put("data/tasks/%s" % task_id, data_dict)`
which works fine with all data except when it comes to the 'assignees', whose id-codes are represented in a list.
Zou then throws an error:
```A server error occured!

Server stacktrace:
Traceback (most recent call last):
  File "/opt/zou/zouenv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request                    
    rv = self.dispatch_request()
  File "/opt/zou/zouenv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request                         
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/zou/zouenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 477, in wrapper                      
    resp = resource(*args, **kwargs)
  File "/opt/zou/zouenv/lib/python3.6/site-packages/flask/views.py", line 84, in view                                     
    return self.dispatch_request(*args, **kwargs)
  File "/opt/zou/zouenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 587, in dispatch_request             
    resp = meth(*args, **kwargs)
  File "/opt/zou/zouenv/lib/python3.6/site-packages/flask_jwt_extended/view_decorators.py", line 38, in wrapper           
    return fn(*args, **kwargs)
  File "/opt/zou/zouenv/lib/python3.6/site-packages/zou/app/blueprints/crud/base.py", line 262, in put                    
    instance.update(data)
  File "/opt/zou/zouenv/lib/python3.6/site-packages/zou/app/models/base.py", line 153, in update                          
    setattr(self, key, value)
  File "/opt/zou/zouenv/lib/python3.6/site-packages/sqlalchemy/orm/attributes.py", line 229, in __set__                   
    instance_dict(instance), value, None)
  File "/opt/zou/zouenv/lib/python3.6/site-packages/sqlalchemy/orm/attributes.py", line 1105, in set                      
    initiator=evt)
  File "/opt/zou/zouenv/lib/python3.6/site-packages/sqlalchemy/orm/collections.py", line 762, in bulk_replace             
    appender(member, _sa_initiator=initiator)
  File "/opt/zou/zouenv/lib/python3.6/site-packages/sqlalchemy/orm/collections.py", line 1044, in append                  
    item = __set(self, item, _sa_initiator)
  File "/opt/zou/zouenv/lib/python3.6/site-packages/sqlalchemy/orm/collections.py", line 1016, in __set                   
    item = executor.fire_append_event(item, _sa_initiator)
  File "/opt/zou/zouenv/lib/python3.6/site-packages/sqlalchemy/orm/collections.py", line 680, in fire_append_event        
    item, initiator)
  File "/opt/zou/zouenv/lib/python3.6/site-packages/sqlalchemy/orm/attributes.py", line 970, in fire_append_event         
    initiator or self._append_token or self._init_append_token())
  File "/opt/zou/zouenv/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 43, in append                     
    item_state = attributes.instance_state(item)
AttributeError: 'str' object has no attribute '_sa_instance_state'

Error message:
'str' object has no attribute '_sa_instance_state'
```
Googling the issue I found somewhere that it expects a `map`-object. But replacing the list with
`map(lambda x:x, ["<Person-id>"])` doesn't work because `json` cannot interpret that.

Is there a solution?

**Comment by frankrousseau** [comment]
Thank you for reporting this bug. 

You can try to use this route:

**Comment by kguyaux** [comment]
Thanks!! That helped greatly!!
`route = "/actions/persons/%s/assign" % gz_person_dict['id']`
`gazu.task.client.put(route, {'task_ids': [<task_id>]})`
..was what worked for me.

**Comment by frankrousseau** [comment]
Can you make a pull request adding an `assign_task` function to `gazu.task`?
